### ISSUE TITLE
Dotnet CLI Web tool Issue

### ISSUE THREAD

**Issue by Siliconrob** [ServiceStack/docs#46]
Tried to make an empty project using the new `web` tool and it kept erroring out

Command I ran `web new web abc --verbose`

**Output**
```
args: 'new web abc'
APP_SOURCE=sharp-apps Sharp Apps
API: https://api.github.com/repos/NetCoreTemplates/web
API: https://api.github.com/repos/NetCoreTemplates/web/releases
Installing web...
Using cached release: /home/robin/.servicestack/cache/https:api.github.comreposNetCoreTemplateswebzipballv11
RMDIR: /tmp/servicestack/web
ExtractToDirectory: /home/robin/.servicestack/cache/https:api.github.comreposNetCoreTemplateswebzipballv11 -> /tmp/servicestack/web
Directory Move: /tmp/servicestack/web/NetCoreTemplates-web-4cea171 -> /mnt/c/projects/abc
System.IO.IOException: Invalid cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Web.Startup.HandledCommandAsync(String tool, String[] args) in C:\src\dotnet-tools\dotnet-app\src\Web\Startup.cs:line 1057
   at Web.Startup.CreateWebHost(String tool, String[] args, WebAppEvents events) in C:\src\dotnet-tools\dotnet-app\src\Web\Startup.cs:line 310
   at Web.Program.Main(String[] args) in C:\src\dotnet-tools\dotnet-app\src\Web\Program.cs:line 14
```

So I then ran this command `mv /tmp/servicestack/web/NetCoreTemplates-web-4cea171/ /mnt/c/projects/abc`  which moved the extracted template folder like I thought it would, although no template renaming happened like I would have liked i.e. **abc** instead of the defaults saying **MyApp**

**Web tool version**
```
Version: 0.0.23
```

I am running this on **Windows Subsystem for Linux Ubuntu 18.04**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
**DotNet Core**
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.202/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.202 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mythz** [comment]
I ran this:

> web new web abc --verbose

On both Windows and Linux Ubuntu which installs without issue. 

Don't run this in WSL as it's not a supported environment for .NET Core and is an immature and incomplete linux environment.

Please submit future issues to https://github.com/ServiceStack/Issues - this is repo is only for issues with docs.
